### ISSUE TITLE
ArcSlider should also support onDragStop.

### ISSUE THREAD

**Issue by iamsolankiamit** [balena-io-modules/rendition#1014]
**Is your feature request related to a problem? Please describe.**
ArcSliders `onValueChange` gets called every time the value changes, there is no way to know when the user has completed his action.

**Describe the solution you'd like**
If ArcSlider has a method like `onDragStop` which get's called once the user stops dragging, one can call expensive function after it, instead of calling every time the values changes.

**Describe alternatives you've considered**
Not much to consider apart from throttling or debouching the value change function.

**Comment by LucianBuzzo** [comment]
Hi @iamsolankiamit thanks for opening the issue. Please see my comment here as to why I'd prefer to use a throttle or debounce approach https://github.com/balena-io-modules/rendition/issues/970#issuecomment-531720722
