### ISSUE TITLE
Add support for 'active step' in Steps component

### ISSUE THREAD

**Issue by grahammcculloch** [balena-io-modules/rendition#1077]
**Is your feature request related to a problem? Please describe.**
See [Jellyfish issue 3318](https://github.com/product-os/jellyfish/issues/3318). 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/2925657/76590815-f448ec00-6520-11ea-8266-d05cc0542817.png)
In the above screenshot its really not clear that the user is on Step 1. It would be nice if we could pass in an `activeStepIndex` property to Steps, that would highlight the active step in a prominent way.

**Describe alternatives you've considered**
I considered adding my own styling but I can't pass in my own class name to the `Step` components and because Rendition uses styled-components, I can't target any of the existing classes for styling.

**Comment by grahammcculloch** [comment]
Here's my work in progress (previous/next buttons are just for the benefit of the storybook story) ....
![Active Steps](https://user-images.githubusercontent.com/2925657/76606503-ef962f00-6544-11ea-8129-82da5d08b06c.gif)

@sradevski thoughts?

**Comment by sradevski** [comment]
@grahammcculloch This might be a design question more than anything else. I would guess it makes sense only the first incomplete step to be highlighted, is that reasonable assumption? I think we can do the following:
1. Allow numbering of steps (a number in the circle).
2. When a step is done, put a green checkmark icon in the place of the number
3. When the step is to be done next, fill the number circle with some color (blue, for example)
4. When the step is neither done, nor next in line, only show an outlined circle with the number inside using a grayish opaque color

What do you think? I'd suggest you ping Alexandra in flowdock and discuss about which approach would work best.

**Comment by grahammcculloch** [comment]
Fixed with #1094
