### ISSUE TITLE
filters search bar regression

### ISSUE THREAD

**Issue by JSReds** [balena-io-modules/rendition#1090]
**Describe the bug**
The filters search bar no longer updates view search

**To Reproduce**
1. Go to Filters section
2. Click on the search bar
3. Type something
4. See that the list is not filtered anymore

**Expected behavior**
the filter list should be filtered when something is written in the search bar

**Screenshots**
<img width="1173" alt="Screenshot 2020-03-31 at 20 10 40" src="https://user-images.githubusercontent.com/7238159/78060371-b6a2ea80-738b-11ea-82e3-d595e559630a.png">

**Specifications (please complete the following information):**
  - Browser:  Chrome Version 80.0.3987.149
  - OS: macOS 10.15.2

**Additional context**

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by magiconair** [comment]
This also affects the filtering in the terminal windows.

**Comment by JSReds** [comment]
solved with #1092
