### ISSUE TITLE
Fixup UI issues caused by Source Sans Pro

### ISSUE THREAD

**Issue by StefKors** [balena-io-modules/rendition#1123]
After switching to Source Sans Pro in this PR https://github.com/balena-io-modules/rendition/pull/1120 there will be UI text that doesn't render/align correctly. This issue collects these problems to be fixed in a single PR.

**Comment by StefKors** [comment]
inline codeblocks don't look correct
<img width="477" alt="Screenshot 2020-06-09 at 14 49 21" src="https://user-images.githubusercontent.com/11800807/84149253-73868700-aa60-11ea-9ad1-906e563c9960.png">

**Comment by sradevski** [comment]
@StefKors is there anything else? Maybe we can fix what is currently causing a problem and open individual issues for whatever else we hit?

**Comment by StefKors** [comment]
@sradevski I haven't ran into anything else on the Jellyfish side. Agree, let's fixup this and we can open issue if we run into things later on.

**Comment by sradevski** [comment]
Haven't noticed any issues, closing
