### ISSUE TITLE
Support for Next.js

### ISSUE THREAD

**Issue by johnnypea** [balena-io-modules/rendition#1164]
What is the recommended way to use your UI components with Next.js?

This example page:
```
import { Button, Box, Provider } from "rendition";

export default function Test() {
  return (
    <Provider>
      <Box my={3} mx={["auto", 15]}>
        <Button primary emphasized>
          Click me
        </Button>
      </Box>
    </Provider>
  );
}
```
Throws this error:
```
./node_modules/highlight.js/styles/default.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/rendition/dist_esm5/extra/Markdown/index.js
```

Relevant discussion https://github.com/vercel/next.js/issues/12079

From a documentation https://github.com/vercel/next.js/blob/master/errors/css-npm.md

Thank you!

**Comment by sradevski** [comment]
Hey @johnnypea thanks for reaching out. I opened a PR that should resolve the issue above: https://github.com/balena-io-modules/rendition/pull/1165. Can you try the branch build (`npm i rendition@16.3.1-dont-import-css-modules-26dc1da4f278a249b27eec0acfafa3f727b2ec73`) and see if it works for you? Let me know if you hit other issues, I'd be  more than happy to get rendition working with Next.js.

**Comment by sradevski** [comment]
@johnnypea FYI, the PR has been merged, so you can try the latest release now. I'll close this, for the time being, and if there are still issues, you can just open a new issue with the concrete problem you are facing. Cheers!

**Comment by johnnypea** [comment]
@sradevski thank you very much!
