### ISSUE TITLE
Should rename "All Tags" column to "Tags"

### ISSUE THREAD

**Issue by myarmolinsky** [balena-io-modules/rendition#1325]
The function of the `All Tags` button isn't entirely clear. It shows a column that displays all the tags of an entity but there's a misunderstanding that it actually *toggles* all tags (columns).

**Comment by LucianBuzzo** [comment]
@myarmolinsky Could you be more specific about what component you're referring to? This issue is quite ambiguous

**Comment by myarmolinsky** [comment]
> Could you be more specific about what component you're referring to? This issue is quite ambiguous

Sure. I'm referring to the dropdown menu you see in list views (such as for devices and apps). Here is a picture of what I'm talking about specifically:
![image](https://user-images.githubusercontent.com/22177187/124766498-f9dff780-df04-11eb-9989-d7ba284029b0.png)

You can access that dropdown by clicking the cog that can be found all the way at the right of a listview table

**Comment by myarmolinsky** [comment]
Forgot to mention, this was as per July 6th's product call, the notes/summary for which could be found here: https://jel.ly.fish/2ca56416-48fe-4e4e-a851-8b4aaf0cadd3
