### ISSUE TITLE
[table] Unknown event handler property `onSort`. It will be ignored.

### ISSUE THREAD

**Issue by atb00ker** [balena-io-modules/rendition#1329]
**Describe the bug**

While creating a new table, I am seeing `Unknown event handler property onSort. It will be ignored.` in console, even when I am not using `onSort`

**To Reproduce**

1. Create a new create component and the following:
```
<Box my={5} mx={['auto', 15]}>
  <Table
    columns={[
      { field: 'id', label: "ID" }
    ]}
    data={<_YOUR_DATA_>}
  />
</Box>
```
2. Open the console on the browser and load the component.
3. Check the console.logs, it should contain:
```
Warning: Unknown event handler property `onSort`. It will be ignored.
    in div (created by styled.div)
    in styled.div (created by TableBase)
    in div (created by styled.div)
    in styled.div (created by TableBase)
    in TableBase (created by Styled(TableBase))
    in Styled(TableBase) (created by Table)
    in div (created by styled.div)
    in styled.div (created by ForwardRef)
    in ForwardRef (created by Component)
    in Component (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Box)
    in Box (created by Flex)
    in Flex (created by Table)
    in div (created by styled.div)
    in styled.div (created by ForwardRef)
    in ForwardRef (created by Component)
    in Component (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Box)
    in Box (created by Styled(Flex))
    in Styled(Flex) (created by Table)
    in Table (created by Home)
    in div (created by styled.div)
    in styled.div (created by ForwardRef)
    in ForwardRef (created by Component)
    in Component (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Box)
    in Box (created by Home)
    in ErrorBoundary (created by Home)
    in Home (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in div (created by StyledGrommet)
    in StyledGrommet (created by Grommet)
    in Grommet (created by Styled(Grommet))
    in Styled(Grommet) (created by BaseProvider)
    in BreakpointProvider (created by BaseProvider)
    in BaseProvider (created by App)
    in App
```

**Expected behavior**

No error should be visible.

**Specifications (please complete the following information):**
  - Browser: Mozilla Firefox 78.11.0esr
  - OS:  Debian 4.19.194-2 (2021-06-21) 
  - Environment: devenv

**Comment by ELIJAHKUNGU** [comment]
Hello i am also experiencing the same problem with the video player

import React from "react";
import styled from "styled-components";
import { BsArrowLeft } from "react-icons/bs";
import { useNavigate } from "react-router-dom";
import video from "../assets/geolocation.mp4";
export default function Player() {
  const navigate = useNavigate();

  return (
    <Container>
      <div className="player">
        <div className="back">
          <BsArrowLeft onClick={() => navigate(-1)} />
        </div>
        <video src={video} autoPlay loop controls muted />
      </div>
    </Container>
  );
}

const Container = styled.div`
  .player {
    width: 100vw;
    height: 100vh;
    .back {
      position: absolute;
      padding: 2rem;
      z-index: 1;
      svg {
        font-size: 3rem;
        cursor: pointer;
      }
    }
    video {
      height: 100%;
      width: 100%;
      object-fit: cover;
    }
  }
`;
