### ISSUE TITLE
Tests to run on CI (GitHub Actions)

### ISSUE THREAD

**Issue by ShaileshKumar007** [balena-io-modules/rendition#1438]
**Is your feature request related to a problem? Please describe.**
Tests not running on push or pull request

**Describe the solution you'd like**
Add GitHub Actions

**Describe alternatives you've considered**
NA

**Additional context**
NA

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by myarmolinsky** [comment]
Closing as we have set up Flowzone with GitHub Actions to test PRs
