### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by hobochild** [balena-io-modules/rendition#145]
I was building a site with resin components and see the bundle size is massive, and around half of if is lodash + react-icons. 

I think this is because we are importing lodash like `import _ from 'lodash'` and `import { icon } from 'react-icons'` we then transpile it to commonjs and webpack only support's tree shaking with es modules `export/import syntax`

@LucianBuzzo have you see similar things with the dashboard bundle? 

The one way to definitely it is do explicit imports like `import filter from 'lodash/filter'`, but open to other ideas?

**Comment by LucianBuzzo** [comment]
@craig-mulligan I think we could probably do a lot just by using explicit imports and taking advantage of tree shaking. I've been hesitant of jumping into bundle size optimization whilst the project is still maturing (though it's always been on my mind).
