### ISSUE TITLE
TypeError: e[this.state.edit.name] is undefined

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#209]
https://github.com/resin-io-modules/resin-components/blob/3f0e365f07b60e2be2558ba6faf3fcca55ec1135/src/components/Filters/index.js#L334-L343

See: https://github.com/resin-io/resin-ui/issues/1595

**Comment by sradevski** [comment]
@thgreasi I believe this is stale and it can be closed.
