### ISSUE TITLE
Should we have a static form control component?

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#213]
Bootstrap provides something such a component and is useful when trying to align text with inputs.
cc: @konmouz @LucianBuzzo

**Comment by LucianBuzzo** [comment]
@thgreasi Can you give an example of what a 'static form control component' is?

**Comment by thgreasi** [comment]
https://getbootstrap.com/docs/3.3/css/#forms-controls-static
:smile: 
A component with sizing that matches those of the Input fields.

**Comment by sradevski** [comment]
All our designs currently feature the label over the input, so we probably won't be adding support for this in the near future
