### ISSUE TITLE
Expose custom `responsiveStyle`s from within utils

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#339]
We are already extending properties (like `max-height` & `max-width`) using `styled-system` `responsiveStyle()` to enable passing multiple values for each window size breakpoint:
* https://github.com/resin-io-modules/rendition/blob/23dcdbaf281e6270231527370a34f9103545c0fe/src/components/Text.js#L18
* https://github.com/resin-io-modules/rendition/blob/e538be901b7e44d4dd27553b3908ef4c6e39a8ec/src/components/Navbar.js#L9-L10
* https://github.com/resin-io-modules/rendition/blob/e538be901b7e44d4dd27553b3908ef4c6e39a8ec/src/components/Container.js#L11

These should probably be located inside utils so that they are reusable within Rendition components.
Exporting them would also give us a simple way to reuse them inside other consumer projects.

**Comment by sradevski** [comment]
The preferred method is exposing a prop as part of the rendition HOC if necessary (we already have height and width-related ones, for example). We can open issues with concrete props that we see are often used. Closing
