### ISSUE TITLE
Move Gauge component out of core library

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#448]
Since `Gauge` relies on a fairly large external package, we should consider moving it to a separate bundle in the `/extra` dir

**Comment by dimitrisnl** [comment]
Is the dependency Chartjs?

**Comment by LucianBuzzo** [comment]
Yep, mainly d3. I think that users can get around it with tree shaking, but it's an extra step that we can avoid.

**Comment by sradevski** [comment]
We removed the 'Gauge' component in #782
