### ISSUE TITLE
Deprecate DeviceStatusGauge component

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#477]
The `DeviceStatusGauge` component is far too specific to the resin.io dashboard, although it was a great example of the power of rendition as frontend toolkit it feels out of place in the current ecosystem. We should migrate this code into the dashboard and remove it from rendition.

**Comment by sradevski** [comment]
Removed in https://github.com/balena-io-modules/rendition/pull/783
