### ISSUE TITLE
Forms component should allow ordering of fields

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#493]
At present we can use the `uiSchema` attribute to set a preferred order for *top level* fields only. This means that ordering sub-objects is impossible. Additionally the Form will thrown an error and not render if a field is listed in the ordering array but isn't present on the object, *or* if a field is present on the object but not listed in the ordering array.

I propose that we add a `fieldOrder` attribute to the form that will accept an array of strings. The strings can correspond to fields in the object you are creating using a lodash style notiation. eg `data.foo.bar`. If a field is not present, it will be silently ignored. Any field not listed in the array will be sorted alphabetically.

To facilitate this change I believe we need to add a custom field widget for the `object` data type.

**Comment by sradevski** [comment]
@LucianBuzzo you can have a nested `ui:order`, why wouldn't that work? And IMO throwing an error if you include something in the order but isn't part of the schema is the expected behavior and it should surface errors sooner. I'll close this but if I missed something feel free to reopen
