### ISSUE TITLE
alert--plaintext: the icon is not aligned with the provided text children

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#523]
**Describe the bug**
The plaintext alert icons aren't perfectly aligned with any provided string content:
![image](https://user-images.githubusercontent.com/1295829/43097937-4afaa68e-8ec6-11e8-8656-c1c9e091b3bf.png)

The solution should preserve the current multiline wrapping of the text (so using flex isn't a solution probably). We might be able to wrap any string text content with a middle aligned `<span>`, but that will not work great if consumers are already providing a custom text `prefix`.

**To Reproduce**
1. Go to [the plaintext alert story](https://resin-io-modules.github.io/rendition/?selectedKind=Core%2FAlert&selectedStory=Plaintext&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Expected behavior**

**Screenshots**

**Specifications (please complete the following information):**
  - Browser: whatsmybrowser.org/b/9F9MAJ4
  - Browser: whatsmybrowser.org/b/GMPGHGT

**Comment by LucianBuzzo** [comment]
@thgreasi Is there a typo in you're bug report? `are perfectly` --> `aren't perfectly`

**Comment by thgreasi** [comment]
@LucianBuzzo yea... I updated the description, thanks for the heads-up :+1:
