### ISSUE TITLE
Flex flexDirection doesn't work with arrays

### ISSUE THREAD

**Issue by DanMMX** [balena-io-modules/rendition#551]
**Describe the bug**
Using `Flex` doesn't work when having `flexDirection` with an array of values (strings)

**To Reproduce**
Run `npm start` on my [forked repo](https://github.com/DanMMX/rendition).

**Expected behavior**
As `Box`, `Flex` claims to accept an array of values which will be activated depending on the viewport size, however the only thing that reacts depending on the viewport size is the `Box`'s width on the modified story (Flex direction)

**Specifications (please complete the following information):**
It's not related to a browser, os or env.

**Comment by sradevski** [comment]
I just checked and everything seems to work as expected. Either a version update to `grid-styled` fixed the issue, or there were some problems with your setup. Feel free to reopen if the issue persists for you, and we can try to figure out what the problem is.
