### ISSUE TITLE
Buttons not aligning properly

### ISSUE THREAD

**Issue by bomberaya** [balena-io-modules/rendition#552]
**Describe the bug**
When two buttons are put in a container, they are not aligned properly

**To Reproduce**
Minimum code to reproduce:
```
import { Button } from 'rendition'
 import FaHome from 'react-icons/lib/fa/home' 
...
// Inside render() method:
<div> 
  <Button color='black'><FaHome /></Button> 
  <Button color='black' iconElement={<FaHome />} /> 
</div>
```

**Expected behavior**
Buttons should be top (and bottom) aligned

**Screenshots**
<img width="184" alt="screen shot 2018-08-14 at 19 34 14" src="https://user-images.githubusercontent.com/3813595/44107877-032a7fe8-9ff9-11e8-9197-a2dbd3e87830.png">

**Specifications (please complete the following information):**
  - Browser: whatsmybrowser.org/b/UAABJ3P
  - OS: OSX 10.11.6 El Capitan

**Comment by LucianBuzzo** [comment]
By default, the `Button` element will expand to accommodate its children, which is one of the reasons we provide the `iconElement` property (which reduces the font size of the passed element). If you'd like the two `Button` components to have a consistent height, you can either reduce the size of `<FaHome />` or reduce the padding of the button.

**Comment by bomberaya** [comment]
I understand that the elements expand to accommodate their children,
but here the buttons actually seem to have exactly same size,
but they are offset by 1px.

Setting `vertical-align` property of `Button` component to `top` instead of `middle` seems to fix it.

Also, I would expect the icons to be the same size by default, regardless of how they were set.
Same goes for the alignment of the elements.

This is just a suggestion, of course, feel free to close the ticket if this is not a valid issue.

**Comment by LucianBuzzo** [comment]
@bomberaya This is a good point. If setting the `vertical-align` property helps this case then a small PR would definitely be worth it.
