### ISSUE TITLE
Implement remaining elements from the styleguide

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#6]
- [x] Inputs
- [x] Dropdowns
- [x] Buttons
- [x] Warnings and alerts
- [x] Modals
- [x] Tables
- [x] Navbar

**Comment by craig-mulligan** [comment]
We have these all now we just need to add examples and conform to style guide.

**Comment by sradevski** [comment]
@LucianBuzzo Looking at storybook it seems everything is implemented and this can be closed. We can open a new ticket when we need to alter the components based on styleguide updates.
