### ISSUE TITLE
Undocumented assumption of "box-sizing: border-box"

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#618]
Rendition component assume that users have a CSS rule like this somewhere in their styles:
```
* {
    box-sizing: border-box;
}
```
However this is undocumented and we don't provide any clear examples on how to implement such a rule. This is how the styling is applied in the storybook: https://github.com/resin-io-modules/rendition/blob/master/.storybook/config.js#L6
Perhaps this could be a style that is automatically applied to any child of the `<Provider>` element?

**Comment by sradevski** [comment]
This is not an assumption anymore as far as I can tell, reopen if it's still an issue.
