### ISSUE TITLE
DropdownButtonProps should extend ButtonProps

### ISSUE THREAD

**Issue by karaxuna** [balena-io-modules/rendition#660]
**To Reproduce**
Assign `plaintext` attribute to DropdownButton.

**Expected behavior**
Typescript understands `plaintext` property from `ButtonProps`, because rest props are assigned to button in dropdown: https://github.com/balena-io-modules/rendition/blob/master/src/components/DropDownButton.js#L155

**Screenshots**
<img width="316" alt="tmp" src="https://user-images.githubusercontent.com/2152815/48672260-2cb70080-eb4d-11e8-823d-79fc92b02759.png">

**Comment by sradevski** [comment]
Done in https://github.com/balena-io-modules/rendition/pull/808
