### ISSUE TITLE
Stored modal screenshots don't show anything

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#665]
The modal screenshots don't show anything, for example, https://github.com/balena-io-modules/rendition/blob/master/__screenshots__/CoreModal-Custom-Button-Properties.png

**Comment by sradevski** [comment]
Note: The same thing is true with other components that depend on some trigger (such as the Tooltip component). We need to find a way to call the trigger in Storybook.

**Comment by LucianBuzzo** [comment]
@sradevski The recommended approach is to detect the screenshot environment in the stories. This is what we do to stop animation of progress bar stories. See https://github.com/balena-io-modules/rendition/blob/master/src/stories/helpers.js
