### ISSUE TITLE
CodeWithCopy component should fail gracefully

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#67]
If the `text` prop is not set the component should try and use the `copy` prop and vice versa.
This will ease problems where you try and shorthand the component and end up with `undefined` in your clipboard.

**Comment by LucianBuzzo** [comment]
Additionally, the component should stringify numbers if they are passed as props

**Comment by sradevski** [comment]
@LucianBuzzo Looking at the code, I think that the `copy` prop is just a message to show as a notification, so I don't think it makes a lot of sense to use that as the text to be copied. Maybe it is better to normalize undefined `text` to an empty string?
