### ISSUE TITLE
For non-joined buttons `onClick` should only trigger for the left part

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#684]
**Describe the bug**
If you add an onClick handler, it will fire for the drop-down toggle too. 

**Expected behavior**
Drop-down toggle should be limited to handling dropdown visibility.

**Additional context**
![screen shot 2018-11-28 at 2 48 02 pm](https://user-images.githubusercontent.com/4951004/49152813-a48ae500-f31c-11e8-9cf9-bc6f2d31a75d.png)

In my case, I want to have the button trigger a download for a specific release. Due to Firefox being very strict with the HTML specs, we can't have a link as a label (anchor inside a button is no go), so I want to do it programmatically.

I noticed that clicking the drop-down toggle would fire the onClick function too making things very complicated.

**Comment by sradevski** [comment]
@dimitrisnl Is this the case? As far as I can see in the code it shouldn't happen. Close if it is not an issue anymore.
