### ISSUE TITLE
Add callback on sort and option to pass default sort options

### ISSUE THREAD

**Issue by sradevski** [balena-io-modules/rendition#691]
The sorting is currently not persisted to local storage. Storing it is useful when users wish to keep the same type of sorting consistently without redoing it over and over again.

**Comment by LucianBuzzo** [comment]
@sradevski I think storage solutions are out of scope for this module.

**Comment by sradevski** [comment]
@LucianBuzzo In that case we need to have a callback on sort, as well as provide the option to pass sorting options. Does that sound like a better alternative?

**Comment by LucianBuzzo** [comment]
@sradevski yes definitely

**Comment by sradevski** [comment]
@LucianBuzzo  I am thinking between these two:
1. Allow to pass default sort options that are used only when the table is mounted, but subsequent renders will use the internal table state
2. Allow to pass sort options that will control the sorting throughout the entire table lifetime.

I personally prefer number 1 as it removes the need to pass sorting props around in the users' code. What do you think?
