### ISSUE TITLE
Fresh installation fails

### ISSUE THREAD

**Issue by cyplo** [balena-io-modules/rendition#694]
Fresh installation fails.

**To Reproduce**
```bash
npx create-react-app my-app
cd my-app
npm install --save rendition
rm -f src/App.js
cat <<EOF > src/App.js
import React from 'react'
import ReactDOM from 'react-dom'
import { Button, Box, Provider } from 'rendition';

ReactDOM.render(
  <Provider>
    <Box my={3} mx={['auto', 15]}>
      <Button primary emphasized>Click me</Button>
    </Box>
  </Provider>,
  document.getElementById('root')
);
EOF
npm run build

> my-app@0.1.0 build /home/cyryl/dev/balena/reconfix/temp/my-app
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/rendition/dist/components/Terminal.js
Cannot find module: 'xterm/dist/addons/fit/fit'. Make sure this package is installed.

```

Maybe having this as a test on CI would be helpful ? What do you think ? If so - I can make a PR with that.

**Additional context**
It seems to be caused by `xterm 3.9.0` changing the path to the addons from `dist` to `lib`
See #693 - alternatively - pinning `xterm` at max `3.8.0` also helps.

**Comment by LucianBuzzo** [comment]
@cyplo Thanks for the research, looks like you PR https://github.com/balena-io-modules/rendition/pull/693/files is the right way forward. A tool like greenkeeper or similar could help catch this stuff.

**Comment by cyplo** [comment]
Heya @LucianBuzzo @thundron - do you want to keep this issue open till we have some tests for these types of issues ? Is there a simple test that we could add quickly ? thanks :)

**Comment by LucianBuzzo** [comment]
@cyplo Since the main point of this issue is resolved, I'm going to close this in favor of https://github.com/balena-io-modules/rendition/issues/690
