### ISSUE TITLE
Sorting table column is case sensitive

### ISSUE THREAD

**Issue by karaxuna** [balena-io-modules/rendition#712]
**Actual behavior**
e, P, E is sorting order

**Expected behavior**
Should be case insensitive by default (e, E, P)

Appears to be related to lodash's sortBy method which sorts case sensitive way by default.

**Comment by imrehg** [comment]
@karaxuna any update on this one yet?

**Comment by karaxuna** [comment]
@imrehg was not assigned to anyone, so did not remember about it. Assigned to myself and will fix it as soon as I finish my current tasks. Thanks for reminding Greg.

**Comment by imrehg** [comment]
Thanks @karaxuna, really appreciate it :)

**Comment by myarmolinsky** [comment]
![image](https://user-images.githubusercontent.com/22177187/139487170-78312953-5b6e-4fce-bb11-9ab049b67996.png)
Appears to no longer be an issue. Closing this ticket.
