### ISSUE TITLE
How do you set responsive breakpoints in Box component?

### ISSUE THREAD

**Issue by GasimGasimzada** [balena-io-modules/rendition#735]
I can't find anything in documentation.

Thanks!

**Comment by LucianBuzzo** [comment]
@GasimGasimzada Rendition uses [styled-system](https://github.com/jxnblk/styled-system#responsive-style-props) which allows you to provide shorthand props as arrays. The array indexes should correspond to the breakpoints defined in the [theme](https://github.com/balena-io-modules/rendition/blob/master/src/theme.ts#L85).
For example:
```
<Box p={[ 1, 2, 3 ]} />
```

**Comment by GasimGasimzada** [comment]
Thank you!
