### ISSUE TITLE
Remove momentjs to reduce bundle size

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#760]
We don't use moment extensively. Can try date-fs.

![screen shot 2019-02-27 at 7 33 48 pm](https://user-images.githubusercontent.com/4951004/53510448-abb1c280-3ac6-11e9-8dfb-4dd06087b0aa.png)

![screen shot 2019-02-27 at 7 34 52 pm](https://user-images.githubusercontent.com/4951004/53510585-064b1e80-3ac7-11e9-9d3b-301b3e647612.png)

thoughts @sradevski 	@LucianBuzzo

**Comment by dimitrisnl** [comment]
Or just drop it. We can write a function ourselves if we only want this operation

```js
// Normalize a timestamp to a RFC3339 timestamp, which is required for JSON
// schema.
// https://momentjs.com/docs/#default-format
const normalizeDateTime = memoize((timestamp: string) =>
	moment(timestamp)
		.utc()
		.format(),
);
```

**Comment by sradevski** [comment]
@dimitrisnl It sounds good to me, if we only use it in just one place. No need to bloat rendition unnecessarily. Let's see what Lucian thinks.

**Comment by LucianBuzzo** [comment]
@dimitrisnl @sradevski I'm happy to drop moment for something smaller here.

**Comment by JackuB** [comment]
Moment is still used in Mermaid, so keeping this issue opened.

**Comment by sradevski** [comment]
We are not using moment directly in rendition, and moment will only be imported if users use mermaid. I will close this as it is not really actionable. We can investigate bundle size later on if it proves to be a problem.
