### ISSUE TITLE
Add support for oneOf in filter

### ISSUE THREAD

**Issue by karaxuna** [balena-io-modules/rendition#761]
**Is your feature request related to a problem? Please describe.**
I want to filter records by slug, but want to show user friendly name in filter dropdown.

**Describe the solution you'd like**
```
nationality: {
    title: 'Nationality',
    oneOf: [{
        title: 'South African',
        const: 'south_african',
    }, {
        title: 'New Zealand',
        const: 'new_zealand',
    }],
}
```

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by sradevski** [comment]
This was done AFAIK, closing.
