### ISSUE TITLE
JellyForm: "pattern properties" object rewrites value of empty key

### ISSUE THREAD

**Issue by zrzka** [balena-io-modules/rendition#786]
**To Reproduce**

1. Open [Reconfix playground](https://balena-io-playground.github.io/reconfix-play/)
2. Select `000 balena os.yaml` from Examples
3. Scroll down to _udev rules*_
4. Type `foo` into the 1st _Rule_
5. Keep the _Key_ for the 1st rule empty
6. Click on the 2nd _Rule_ textfield
7. Type `bar`
7.1. `b` -> 1st rule changes to `b`, 2nd rule is empty & focused
7.2. `a` -> 1st rule changes to `a`, 2nd rule is empty & focused
7.3. `r` -> 1st rule changes to `r`, 2nd rule is empty & focused

**Expected behavior**

Ability to enter the 2nd rule even if the _Key_ for the 1st rule is empty.

**Screenshots**

![udev-foo-bar-safari](https://user-images.githubusercontent.com/1084172/54756723-19926b00-4be9-11e9-9d56-162be604e935.gif)

**Specifications (please complete the following information):**

* Browser
  * Safari - https://whatsmybrowser.org/b/QCH3X6V
  * Firefox - https://whatsmybrowser.org/b/V3T24HV
* OS: macOS 10.14.3 (18D109)

**Comment by sradevski** [comment]
We removed JellyForm from rendition, closing
