### ISSUE TITLE
JellyForm: "pattern properties" object is swapping key & value rows and overwriting another row value

### ISSUE THREAD

**Issue by zrzka** [balena-io-modules/rendition#787]
**To Reproduce**

1. Open [Reconfix playground](https://balena-io-playground.github.io/reconfix-play/)
2. Select `000 balena os.yaml` from Examples
3. Scroll down to _udev rules*_
4. Type `foo` into the 1st _Rule_
5. Type `10` into the 1st _Key_
6. Click on the 2nd _Rule_ textfield
7. Type `bar`

* _Key_ & _Rule_ rows are swapped visually
* 1st rule - _Key_ is empty, _Rule_ contains `b`
* 2nd rule - _Key_ contains `10`, _Rule_ contains `fooar`

**Expected behavior**

* Do not swap them visually
* Do not overwrite _Rule_ in another field

**Screenshots**

Firefox exhibiting the problem:

![foo-bar-priority-udev-rules](https://user-images.githubusercontent.com/1084172/54757719-18fad400-4beb-11e9-8c4b-f6110d0d13d4.gif)

Same steps works flawlessly in Safari:

<img width="485" alt="Screenshot 2019-03-21 at 15 03 02" src="https://user-images.githubusercontent.com/1084172/54757660-f963ab80-4bea-11e9-93f1-022459cfae54.png">

**Specifications (please complete the following information):**

* Browser
  * Safari - https://whatsmybrowser.org/b/QCH3X6V  
  * Firefox - https://whatsmybrowser.org/b/V3T24HV
* OS: macOS 10.14.3 (18D109)

**Comment by sradevski** [comment]
We removed JellyForm from rendition, closing
