### ISSUE TITLE
Plain buttons have an underline

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#825]
![May-02-2019 12-27-03](https://user-images.githubusercontent.com/4951004/57066746-be6a9280-6cd5-11e9-9c55-b813762a66d9.gif)

**Comment by dimitrisnl** [comment]
I would expect to have a Button state where it's completely unstyled. No borders and no underlines

**Comment by dimitrisnl** [comment]
Example: https://balena-io-modules.github.io/rendition/?selectedKind=Core%2FTable&selectedStory=Standard&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

Hover of the header elements

**Comment by LucianBuzzo** [comment]
We've discussed this internally and decided to apply the `light` variant of a color on hover.
