### ISSUE TITLE
Should drop package.lock file

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#840]
Having a lock file conceals what a new user gets when installing rendition.
Since the package.lock isn't part of the published npm package, a fresh consumer (or a consumer that upgrade their projects dependencies which are shared with rendition) can end with a problematic package tree in which rendition isn't ever tested against and might be broken.
In that case the user will have issues even though our CI tests still pass.

**Comment by dimitrisnl** [comment]
More on this https://www.twilio.com/blog/lockfiles-nodejs
