### ISSUE TITLE
Improve button styles

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#845]
- Make the 'Primary' button (light blue shade) the default button.
- Introduce a 'Light' button variant as seen in Zeplin designs
- Ensure that the disabled button doesn't have any hover effects
- Hovered button has the same look as a disabled on. Should probably apply a darker shade as opposed to a light one.

**Comment by dimitrisnl** [comment]
@LucianBuzzo @sradevski

**Comment by dimitrisnl** [comment]
https://github.com/balena-io-modules/rendition/pull/844

**Comment by sradevski** [comment]
The only thing left to do is change the `default` button. How about making `secondary outline` as the default button for now, as it is the closest to the current `default` one and we don't have to make a bunch of changes across projects?

**Comment by dimitrisnl** [comment]
I agree @sradevski
