### ISSUE TITLE
Recreate Input component with Grommet

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#848]

**Comment by dimitrisnl** [comment]
https://v2.grommet.io/textinput

**Comment by LucianBuzzo** [comment]
@dimitrisnl It makes sense to have separate components here, even if it requires a breaking change

**Comment by sradevski** [comment]
The only thing I would like is to batch breaking changes so we don't have to do breaking change fixes across our projects all the time.

**Comment by LucianBuzzo** [comment]
@sradevski surely if you don't want to update dependant projects all the time then you would simply wait for a number of major releases to happen before updating?
