### ISSUE TITLE
Add a simple utility for checking if fontawesome pro icons are available

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#854]

**Comment by dimitrisnl** [comment]
I don't think it's that straightforward.

The icons can 1) be pulled in by CDN, 2) be self-hosted or 3) be installed using a package manager.

I have a hard time thinking of a catch-all solution.

I believe it would be better to have a config option `useFaPro: boolean` and use the appropriate icon class names.

**Comment by LucianBuzzo** [comment]
@dimitrisnl It's pretty straightforward to check if a font is loaded or not - here is a nice example using canvas https://stackoverflow.com/a/24618517/8583153
I looked through the docs and since loading the FA pro module requires authentication at the npm level, requiring the end user to load fontawesome themselves seems like the best way forward. As long as we make this clear in our installation/usage documentation I don't think its a problem.

**Comment by dimitrisnl** [comment]
@LucianBuzzo 	You can also generate CDN links in the dashboard, but that's not important, we'll cover that case too. I agree that the best way to do it - thanks for the link 👍

**Comment by sradevski** [comment]
The free version of font-awesome is sufficient for now and matches our designs, we can reopen in the future if necessary.
