### ISSUE TITLE
ButtonSwitch has a strange behaviour when using less than 3 buttons

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#862]
![May-30-2019 15-08-14](https://user-images.githubusercontent.com/4951004/58632094-5c5d7700-82ed-11e9-99fd-ea5ed99b7b7f.gif)

**Comment by dimitrisnl** [comment]
```js
<ButtonGroup>
  <Button
    primary
    outline={option1.value !== active}
    onClick={() => onClick(option1.value)}
  >
    {option1.name}
  </Button>
  <Button
    primary
    outline={option2.value !== active}
    onClick={() => onClick(option2.value)}
  >
    {option2.name}
  </Button>
</ButtonGroup>
```

**Comment by dimitrisnl** [comment]
I believe that's because the buttons have a `transition: 0.1s ease-in-out;` style, that includes the border-radius.

**Comment by dimitrisnl** [comment]
@sradevski 	A workaround is to apply `style={{ transition: 'none' }}`.

Considering the effect in the above scenario is that of a `Toggle`, it doesn't make sense to me to patch the `ButtonSwitch` component.

**Comment by sradevski** [comment]
I think just applying a transition to all properties is bad on its own, but we can maybe submit a PR for that in Grommet. But why do the right-side borders change at all so a transition is shown? A workaround would be to override this in our button and only apply the transition to several properties. Let's discuss it later.

**Comment by dimitrisnl** [comment]
Agreed, a good start would be submitting a proposed solution in Grommet.

From what I remember, when I change the `outline` property, the classnames change too. The one which holds the transition property gets re-applied which triggers the transition from the start.

**Comment by dimitrisnl** [comment]
PR in Grommet https://github.com/grommet/grommet/pull/3152
