### ISSUE TITLE
DropDownButton has white font-color on hover

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#876]
The text will always be white on hover, even if we override it with `color='x'`

![Jun-20-2019 10-47-48](https://user-images.githubusercontent.com/4951004/59830766-f9d62480-9348-11e9-827b-9711d51491ec.gif)

![Jun-20-2019 10-47-54](https://user-images.githubusercontent.com/4951004/59830768-f9d62480-9348-11e9-927a-6fbac5b86427.gif)

**Comment by dimitrisnl** [comment]
Might also be nice changing the vertical padding. It seems a bit off having that much space.

**Comment by dimitrisnl** [comment]
How the custom one looks in the website:

**Comment by dimitrisnl** [comment]
Updates:

- The carret color should match the font color
- The right padding can be reduced

**Comment by dimitrisnl** [comment]
The problem comes from the Button component

https://github.com/balena-io-modules/rendition/blob/master/src/components/Button.tsx#L53-L56

as we ignore any `color` property and use white no matter what.

Thoughts @sradevski 	?

**Comment by sradevski** [comment]
@dimitrisnl since we allow the background to be overridden, it makes sense to fix it so the `color` prop is also respected, otherwise it makes no sense to even have it as a prop in the first place. Just fix whatever is needed so it works as one would expect.

**Comment by myarmolinsky** [comment]
Closing this ticket as we no longer default the color to white. Instead, we know determine whether to use white or the main text color from the theme depending on the color prop (`bg`) passed into it.
