### ISSUE TITLE
Sort out tags and badges

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io-modules/rendition#923]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by dimitrisnl** [comment]
@LucianBuzzo 	I know this is a placeholder issue, and we have discussed it a lot in the calls. Are there something specific we can do right now?
