### ISSUE TITLE
ComponentWIllReceiveProps is now deprecated.

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io-modules/rendition#944]
As of 16.9.0 (August 8, 2019) both this and [some other lifecycle](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html) methods will still work but will throw some warnings.

In the next major release, we have to append the `UNSAFE_` prefix, if we want to keep the same functionality. Ideally, we should refactor any instance that uses these methods.

**Comment by dimitrisnl** [comment]
https://github.com/balena-io-modules/rendition/search?q=componentWillReceiveProps&unscoped_q=componentWillReceiveProps

**Comment by dimitrisnl** [comment]
runnin `npx react-codemod rename-unsafe-lifecycles` will do the patch fix too.

**Comment by alexandrtovmach** [comment]
@dimitrisnl Please take a look to my PR that's refactor deprecated hooks #968

**Comment by alexandrtovmach** [comment]
Fixed by #968 . Issue should be closed
