### ISSUE TITLE
Add defaultValue or initialValue for <ArcSlider />

### ISSUE THREAD

**Issue by alexandrtovmach** [balena-io-modules/rendition#967]
I faced with a problem to set initial value to `<ArcSlider />`. In current verion just `value` property is available.

In case of `value` usage I should write an additional handler to update it every time, but for example I just want to provide initial value, and then just listen `onValueChange` callback.

**Comment by sradevski** [comment]
We have plans of dropping the ArcSlider component, so we won' be fixing anything

**Comment by LucianBuzzo** [comment]
@sradevski Can we just go ahead and drop the `ArcSlider`?

**Comment by sradevski** [comment]
@LucianBuzzo yeah, https://github.com/balena-io-modules/rendition/pull/1231
