### ISSUE TITLE
ArcSlider is unable to prevent passive event.

### ISSUE THREAD

**Issue by barrard** [balena-io-modules/rendition#972]
**Describe the bug**
The `ArcSlider` component uses the `ontouchstart` and `ontouchmove` events to handle the slider on touch screens, and `event.preventDefault()` to disable scrolling.  However, `React` does not  [Support Passive Event Listeners #6436](https://github.com/facebook/react/issues/6436)

![](https://media.giphy.com/media/QTyNUkaPjM38jNEf9z/giphy.gif)

**To Reproduce**
1. Go to Rendition story book [ArcSlider](https://balena-io-modules.github.io/rendition/?selectedKind=Core%2FArcSlider&selectedStory=Standard&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) on a touch-enabled device.
2. Touch the `Arcslider` and attempt to slide.

**Expected behavior**
The `ArcSlider` should prevent scrolling and enable the user to easily adjust the slidder.

**Screenshots**
![](https://i.postimg.cc/sXkn7vFr/image.png)

**Specifications (please complete the following information):**
  - Browser: [Chrome 76](whatsmybrowser.org/b/CQW74TZ)
  - OS: Ubuntu 18.04.3 LTS
  - Environment: devenv
  
**Additional context**
This has been an issue since Chrome 56 as seen here in  `react` issues [Chrome 56 breaks touch events #8968](https://github.com/facebook/react/issues/8968)
And here is Google's explanation about the changes they made to [Improve Scrolling performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention)

**Comment by sradevski** [comment]
We have plans of dropping the ArcSlider component, so we won' be fixing anything
