### ISSUE TITLE
Filters: User wants the search input to also search for tag keys/values

### ISSUE THREAD

**Issue by thgreasi** [balena-io-modules/rendition#986]
**Is your feature request related to a problem? Please describe.**
User wants to be able to use the fitler's search input to filter the results based on their associated tags.

**Describe the solution you'd like**
The user would prefer if the text in the search input was also checked against the associated tags of each item.

**Describe alternatives you've considered**
Even though it works, the user mentioned that it's not that convenient to use the "Add filter" modal when they need to search for a tag.

**Additional context**
See: https://github.com/balena-io/resin-ui/issues/3113
See: https://forums.balena.io/t/34595

**Comment by myarmolinsky** [comment]
I believe resolved by #1573
